### ISSUE TITLE
Header CSS is not good

### ISSUE THREAD

**Issue by lakshyatyagi24** [lakshyatyagi24/Furniture-Website#3]
1.

**Comment by ShobhitRathi** [comment]
will fix it you can assign me. just to confirm you are talking about index.html right?

**Comment by lakshyatyagi24** [comment]
header need to be fixed on all website

**Comment by ShobhitRathi** [comment]
ok ill first fix the header for index and you can check it

**Comment by lakshyatyagi24** [comment]
yes that's perfect
