### ISSUE TITLE
Some of the Links are broken or not working

### ISSUE THREAD

**Issue by oneofthedevs** [lakshyatyagi24/Furniture-Website#9]
Some of the Links (e.g. navbar in contact us page) are broken

**Comment by andyantunes** [comment]
Hey @oneofthedevs, can i work on this issue? 
If yes, assign it to me please.

**Comment by lakshyatyagi24** [comment]
Sure @andyantunes you can contribute in it

**Comment by andyantunes** [comment]
It's just on the page contact us?

**Comment by lakshyatyagi24** [comment]
> It's just on the page contact us?

@oneofthedevs can you please let him know

**Comment by oneofthedevs** [comment]
@andyantunes No, it's probably on every page except for index but I would recommend checking each page, will probably take like 10-15mins max

**Comment by andyantunes** [comment]
@oneofthedevs Ok, I'll check the other pages too
